apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: planning-app
  namespace: planning-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: planning-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
